[package]
name = "i3bg"
version = "0.1.0"
authors = ["Kyuuhachi <caagr98@gmail.com>"]
edition = "2018"

[dependencies]
i3ipc = "0.10.1"
x11rb = { version="0.8.0", features=["image"] }
image = { version="0.23.2", default-features=false, features=["png"] }
